### PR TITLE
Package as DIT for use in DABL

### PR DESCRIPTION
**Pull request by mschaef-da**

### CODE REVIEW

**Review by dimitri-da — APPROVED** [review]
LGTM. Adding @leonidr-da who is the author of this just to make sure I didn't miss anything

**Comment by leonidr-da** [comment]
@mschaef-da Are we removing the version's because the `dabl-meta.yml` file doesn't support them?

**Review by leonidr-da — APPROVED** [review]
I found the versions helpful when developing against DABL, but onerous to manage. Is there a way to keep them?

**Comment by mschaef-da** [comment]
> Is there a way to keep them?

Added back in.

**Pull request merged**
